### ISSUE TITLE
Failed to load assembly

### ISSUE THREAD

**Issue by Kwbmm** [shemanaev/jellyfin-plugin-webhooks#12]
After trying to install the plugin, my Jellyfin instance disables it and I can see the following error in the logs:

```
[2024-02-19 23:10:19.633 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/data/plugins/Webhooks_3.6.2.0/Jellyfin.Webhooks.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Common, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Model, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'Jellyfin.Data, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Common, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Model, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'MediaBrowser.Controller, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'Jellyfin.Data, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Jellyfin.Data, Version=10.8.13.0, Culture=neutral, PublicKeyToken=null'

**Comment by Kwbmm** [comment]
It was enough to trigger an update of Jellyfin!
