### ISSUE TITLE
Live TV

### ISSUE THREAD

**Issue by jaimedelano** [shemanaev/jellyfin-plugin-webhooks#2]
Jellyfin chashes when I open live tv channels with this webhook activated.
I get this error message:

System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Jellyfin.Webhooks.EntryPoint.OnPlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by shemanaev** [comment]
Thanks for reporting.
Should be fixed in [1.0.0.3](https://github.com/shemanaev/jellyfin-plugin-webhooks/releases/tag/v1.0.0.3)
